### ISSUE TITLE
kernel provisioner ('ignition-kernel-provisioner') that is not available

### ISSUE THREAD

**Issue by jasperlg** [ignition-kernel/ignition-kernel#2]
After following all the instructions as good as I can, I get this:

```
[W 2024-09-26 14:36:01.692 ServerApp] Kernel 'localhost-designer' is referencing a kernel provisioner ('ignition-kernel-provisioner') that is not available.  Ensure the appropriate package has been installed and retry.
[W 2024-09-26 14:36:01.700 ServerApp] Kernel 'ignition' is referencing a kernel provisioner ('ignition-kernel-provisioner') that is not available.  Ensure the appropriate package has been installed and retry.
[W 2024-09-26 14:36:01.763 ServerApp] Kernel 'localhost-designer' is referencing a kernel provisioner ('ignition-kernel-provisioner') that is not available.  Ensure the appropriate package has been installed and retry.
[W 2024-09-26 14:36:01.767 ServerApp] Kernel 'ignition' is referencing a kernel provisioner ('ignition-kernel-provisioner') that is not available.  Ensure the appropriate package has been installed and retry.

```

But as far as I know the provisioner should be installed when I did 'python -m ignition_kernel --install --hostname http://localhost:8088' correctly, no? Or what am I missing?

**Comment by jasperlg** [comment]
After retrying a couple of times, I'm a step further, no idea why. Now I tried applying my own server:
`python -m ignition_kernel --install --hostname http://localhost:8088`

But when clicking 'Ignition', I still see it tries to go to port 8043.
<img width="903" alt="Screenshot 2024-09-26 at 16 09 20" src="https://github.com/user-attachments/assets/1f3b0829-07f5-4497-a296-9f5864c563d3">

**Comment by jasperlg** [comment]
I don't know how but it got fixed eventually. 

Now I'm stuck on this error message:
`
[W 2024-09-26 16:27:28.898 ServerApp] wrote error: 'Expecting value: line 1 column 1 (char 0)'
    Traceback (most recent call last):
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/requests/models.py", line 974, in json
        return complexjson.loads(self.text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/sessions/handlers.py", line 90, in post
        s_model = await sm.create_session(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 285, in create_session
        kernel_id = await self.start_kernel_for_session(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 343, in start_kernel_for_session
        kernel_id = await self.kernel_manager.start_kernel(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 233, in _async_start_kernel
        kernel_id = await self.pinned_superclass._async_start_kernel(self, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_client/multikernelmanager.py", line 283, in _async_start_kernel
        raise km.ready.exception()  # type: ignore[misc]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_client/multikernelmanager.py", line 232, in _add_kernel_when_ready
        await kernel_awaitable
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 784, in wrapped_method
        raise err
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 748, in wrapped_method
        out = await method(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 853, in start_kernel
        return await super().start_kernel(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_client/manager.py", line 96, in wrapper
        raise e
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_client/manager.py", line 87, in wrapper
        out = await method(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_client/manager.py", line 439, in _async_start_kernel
        await self._async_launch_kernel(kernel_cmd, **kw)
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_client/manager.py", line 354, in _async_launch_kernel
        connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/ignition_kernel/provisioner.py", line 383, in launch_kernel
        connection_info = response.json()
                          ^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/requests/models.py", line 978, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/sessions/handlers.py", line 108, in post
        raise web.HTTPError(500, str(e)) from e
    tornado.web.HTTPError: HTTP 500: Internal Server Error (Expecting value: line 1 column 1 (char 0))`


I assume this is because Ignition is not sending anything, which I can confirm I only get an empty array on the Get call.
Steps taken: 

- I have already 'HTTPS Required' for the request 
- I added the JAR libraries in '/usr/local/bin/ignition/lib/core/common', as I hope this would be the correct place for that.

 What I did not do:
- place the libraries in the  shared.tools.jupyter.zmq.JAR_FOLDER, since I did not find any folder that looks like this.

**Comment by null-directory** [comment]
I'm not sure what happened in your first comment, as it directly adds the kernel configuration file to Jupyter to use. The fact it worked eventually suggests I need to clarify the process a bit, but I'm not sure what got your install tripped up. Might be an environment issue, though each part should know themselves well enough to not care. Hmm.

As for the second note, yes, that means on launch the kernel was not spun up in Ignition. The 500 error is on Ignition's side where it failed to serve up the kernel's connection details for Jupyter to hook into.

You _shouldn't_ need to manually add the ZMQ jar files as the `jupyter` project in Ignition will automatically download and hotload them as needed. By default it tries to load from the usual Ignition user-lib directory:
> [JAR_FOLDER = './user-lib/pylib'](https://github.com/ignition-kernel/ignition-project/blob/e7d5b800d33305ffa50561621bace951fe6fbee6/resources/python/shared/tools/jupyter/zmq.py#L25)

But placing the needed `jeromq` (Java ZeroMQ) and `jnacl` (crypto) jars in `./lib/core/common` should let it load anyhow on line 112 in `shared.tools.jupyter.zmq.py`

### For connecting to a Designer
If you're attempting to hook Jupyter into a Designer instance (as opposed to a gateway), you'll need to run the following command in a script console. This bootstraps a little webserver that listens for Juypter attempting to launch a new kernel. 

> `>>> shared.tools.jupyter.handlers.web.kernel.launch_designer_kernel_management()`
![image](https://github.com/user-attachments/assets/41f7910b-4ad9-4f15-bae4-7128523bf536)

(Jupyter _must_ always demand the kernel in response to their request - they as policy will not allow you to spin one up and hook into something after the fact. Mostly.)

If you get errors, check the Designer's output console to see what is going wrong and paste it here.

### For connecting to the Gateway
By default, this is how we'd normally expect it to launch. This goes through WebDev and uses the normal HTTP interface to the gateway.

If you get errors, check the gateway logs to see what it's complaining about and paste it here.

**Comment by jasperlg** [comment]
Thanks for your reply. I really want it to see it working! 
When I try to create a new kernal, I get the error as above, but no new logs are appearing in Ignition at all. 

So pretty odd, because when Ignition is down, I get the error: 
`HTTP 500: Internal Server Error (HTTPConnectionPool(host='localhost', port=8088): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d36b200>: Failed to establish a new connection: [Errno 61] Connection refused')))`

So it does go one step further, which should be a connection to Ignition. What could be wrong on the Ignition side without it spitting logs? I have disabled 'Require https' in de Web Dev module, could that be bad?

I didn't know you could use JAR's in the pylib folder, but I do see Ignition has indeed hotloaded those there. 

I mostly tried connecting to the gateway, but I tried connecting to the Script console as well, which does not give a real error in Jupyter, but it just tries to constantly connect, and gives me this in the console: 

`[E 2024-09-27 17:05:36.244 ServerApp] Uncaught exception GET /api/kernels/275cf3eb-2ca6-4c10-ba4a-821ef03d6296/channels?session_id=dc308f33-fd48-4a55-a819-620b9dc3b208 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/api/kernels/275cf3eb-2ca6-4c10-ba4a-821ef03d6296/channels?session_id=dc308f33-fd48-4a55-a819-620b9dc3b208', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/kernels/websocket.py", line 66, in get
        await super().get(kernel_id=kernel_id)
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/tornado/websocket.py", line 273, in get
        await self.ws_connection.accept_connection(self)
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/tornado/websocket.py", line 863, in accept_connection
        await self._accept_connection(handler)
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/tornado/websocket.py", line 903, in _accept_connection
        self.selected_subprotocol = handler.select_subprotocol(subprotocols)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jasperlouage/virtual_env/lib/python3.12/site-packages/jupyter_server/services/kernels/websocket.py", line 88, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
[E 2024-09-27 17:05:36.270 ServerApp] {
      "Host": "localhost:8889",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
    }
[E 2024-09-27 17:05:36.270 ServerApp] 500 GET /api/kernels/275cf3eb-2ca6-4c10-ba4a-821ef03d6296/channels?session_id=dc308f33-fd48-4a55-a819-620b9dc3b208 (da299053dc144d08803cdcbcdd8899c6@127.0.0.1) 60032.87ms referer=None
[W 2024-09-27 17:05:40.456 ServerApp] Nudge: attempt 10 on kernel 275cf3eb-2ca6-4c10-ba4a-821ef03d6296
[W 2024-09-27 17:05:45.476 ServerApp] Nudge: attempt 20 on kernel 275cf3eb-2ca6-4c10-ba4a-821ef03d6296`


You said in your mail it could be something about virtualization as well?

**Comment by maxke24** [comment]
Hi, I have been trying to set this up too and have stumbled on exactly the same problems. I have been able to connect it to the designer but would like to connect it to the gateway but have not yet been successful. I'm currently getting this error: `HTTPSConnectionPool(host='127.0.0.1', port=8043): Max retries exceeded with url: /system/webdev/jupyter/kernel (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000253601CEAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))` and am unable to get past this. Could you provide some more insight as to what the problem could be?

**Comment by marcosverdugob** [comment]
Has anyone solved this issue? I have the same issue as @maxke24 I got the same exact error. Apparently is something of the ilk of using http:// instead of https:// on an ssl port (like 8043). It may also be if you try to connect using IP address over ssl using a cert that expects the host domain name. Basically, the application is willing to talk (so it's not a firewall blackholing your request) but it's unwilling to (probably because of some protocol pedantry).

Has anyone solved the issue?

**Comment by jasperlg** [comment]
I haven't solved it.

**Comment by null-directory** [comment]
Sorry, apparently I didn't have GitHub forwarding ticket updates at me.

I'm not totally sure if there's a consistent/universal root cause, other than it's probably not _wrong_, per se. One of those "this is a bug, and it is correctly failing something subtle" situations that's extremely frustrating to debug. I think @marcosverdugob has the right of it, troubleshooting-wise as that's where I'd be starting.

Basically it's trying to connect and isn't willing to. 

- Ignition will by default block non-HTTPS unless you disable that in WebDev.
- Loading your own HTTP webserver in a designer via `shared.tools.jupyter.handlers.web.kernel.launch_designer_kernel_management()` by default expects HTTP on port 8989 from `localhost`
- If you don't have WebDev installed, the Ignition Tomcat server will fail the connection attempt
- Firewalls may blackhole connection attempts, but those won't be actively refused, so it's _probably_ not the firewall
- Maybe URL capitalization?
- SSL can definitely goober it, especially if the gateway is not running on the IP address that the hostname resolves to, or if the cert is out of date.
- Virtualization can gunk things up too, sometimes. Though that gets complicated fast.

@jasperlg I'm not sure where to go with the virtualization debugging, if only because where the local ports and hostnames resolve can be pretty situational. But I can try to make sense of it, assuming it's still a problem.

I _suspect_ it's not an actual bug in either the setup or handshake, but rather something taken for granted didn't get configured or match up correctly. If you figured it out, holler and I'll try to have the setup autoconfigure it more seamlessly in the future.
